name: deploy.yml
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'insomnia/**'
      - '.gitignore'
      - 'LICENSE'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy to Ec2 via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/
            if [ ! -d "react-app/.git" ]; then
            echo "Cloning repo"
            git clone https://github.com/Farmience-Agrotech/Frontend_2.git react-app
            cd react app
            
            else
            echo "latest changes"
            cd react-app
            git pull origin main
            fi
            
            pm2 describe orkhest > /dev/null
            
            if [ $? -eq 0]; then
              echo "Restarting pm2"
              pm2 delete orkhest
            fi
            
            pm2 serve dist 3000 --name "orkhest" --spa
            sudo systemctl reload nginx